### ISSUE TITLE
listen only to localhost

### ISSUE THREAD

**Issue by beshoo** [loretoparisi/fasttext.js#12]
I think this has to be add , so not DDos Attack to the port !

**Comment by loretoparisi** [comment]
@beshoo you are right, I have added a `host` parameter to the `server.listen`:

```
$ export PORT=3000
$ export HOST=localhost
$ export MODEL=data/lid.176.ftz
$ node server.js 
model loaded
server is listening on 3000
```

Thanks, closing then!
