### ISSUE TITLE
Node installing problem 

### ISSUE THREAD

**Issue by beshoo** [loretoparisi/fasttext.js#13]
hello :)

once i want to run the server file:
node server.js i got this error:
```

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)

```

Please Advice
node -v
v8.11.1
+++++++++++++++++++
npm -v
5.6.0
_____________________________
fasttext.js
Current

**Comment by beshoo** [comment]
SOLVED

**Comment by lmaranhao** [comment]
I'm having the same issue. How have you solved this?

**Comment by loretoparisi** [comment]
@lmaranhao on which platform do you have this issue?
