### ISSUE TITLE
better error message when .bin is not found on load()

### ISSUE THREAD

**Issue by bittlingmayer** [loretoparisi/fasttext.js#15]
Right now it's the following:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:851:14)
```

**Comment by loretoparisi** [comment]
@bittlingmayer thank you to point this out! I have added a file check and an error message/code.
https://github.com/loretoparisi/fasttext.js#external-binary

**Comment by bittlingmayer** [comment]
You should push that to https://www.npmjs.com/package/fasttext.js by the way.

**Comment by loretoparisi** [comment]
@bittlingmayer right, thanks I have to.

**Comment by loretoparisi** [comment]
@bittlingmayer done published with the latest features: train progress tracking and some utilities like confusion matrix calculation!

**Comment by bittlingmayer** [comment]
Great, thanks!
