### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by bittlingmayer** [loretoparisi/fasttext.js#2]
Firstly bravo and thank you for this

I think for this lib to gain momentum, which will ultimately benefit all users, it will be good to put it on npm.

Is it in the plans?  Is there any reason not to?

**Comment by loretoparisi** [comment]
@bittlingmayer yes I'm going to publish via npm asap!

**Comment by loretoparisi** [comment]
@bittlingmayer you can find the npm package here: https://www.npmjs.com/package/fasttext.js
Thank you!

**Comment by bittlingmayer** [comment]
@loretoparisi Thank *you*, I will get it in front of the right people.
