### ISSUE TITLE
I cannot run this project on apple M1 silicon

### ISSUE THREAD

**Issue by QEASONT** [loretoparisi/fasttext.js#29]
## This is Train.js
![Fe58Nh](https://qeasont.oss-cn-beijing.aliyuncs.com/uPic/Fe58Nh.png)

## This is 100_normal_stemming_train.tsv
![LxVMbZ](https://qeasont.oss-cn-beijing.aliyuncs.com/uPic/LxVMbZ.png)

## This is the running result
![Jyk2Ii](https://qeasont.oss-cn-beijing.aliyuncs.com/uPic/Jyk2Ii.png)

## When I try to test the dataset with the model 100_normal_stemming.bin training by fasttext python package, it shows as blow
![rhqjKi](https://qeasont.oss-cn-beijing.aliyuncs.com/uPic/rhqjKi.png)

**Comment by loretoparisi** [comment]
@QEASONT good catch, I will compile against apple silicon. It should work on all Mx series.

**Comment by loretoparisi** [comment]
@QEASONT could you please run the following nodejs code snippet

```javascript
const os = require('os')
let cpuCore = os.cpus()
let isIntel = cpuCore[0].model.includes("Intel")
let isM1 = cpuCore[0].model.includes("Apple")
console.log(isIntel, isM1)
```

to confirm your cpu architecture. Thank you! The build is coming.

**Comment by loretoparisi** [comment]
Support of Apple M1 and M1 Pro is now avaiable .
