### ISSUE TITLE
predict in an AWS Lambda or GCP Function?

### ISSUE THREAD

**Issue by bittlingmayer** [loretoparisi/fasttext.js#3]
Model size makes serverless a bit odd, but in theory it should work fine once the function is called often enough to keep the re-usable container loaded.

Have you tried it and do you plan to support it or do you think it is not doable or not sensical?

https://cloud.google.com/functions/
http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

**Comment by loretoparisi** [comment]
@bittlingmayer thanks I will provide a simple Amazon Lambda example.

**Comment by bittlingmayer** [comment]
@loretoparisi The equivalent for a standard service would be a Docker image or example Docker file, that could also be useful.

**Comment by loretoparisi** [comment]
@bittlingmayer thanks for the suggestion! In the meanwhile take a look at the current Dockerfile here https://github.com/loretoparisi/fasttext.js/blob/master/Dockerfile
I will add the AWS sdk and a simple lambda processing function as well!

**Comment by bittlingmayer** [comment]
I am trying this now on a Cloud function and have a question:

It seems I must call .load() and then call .predict() directly after that and then call .unload, because without .unload it hangs.

But ideally I would call .load() in the init - I assume it's heavy - and then on each request just call .predict().

Am I doing something wrong?

**Comment by bittlingmayer** [comment]
@loretoparisi ping :-)

**Comment by bittlingmayer** [comment]
Made it work now.

The issue was that I had to include this repo directly in the package.json, the latest version up on npm does not work.

**Comment by bittlingmayer** [comment]
Work in progress but here it is: https://github.com/SignalN/ftfn

**Comment by bittlingmayer** [comment]
Now that the fixes to #15 are pushed to npm, I suppose we can close this.
