### ISSUE TITLE
Is there any plan for StarSpace :)

### ISSUE THREAD

**Issue by beshoo** [loretoparisi/fasttext.js#5]
Dear loretoparisi,

I loved your FastText project , and i believe you aim on StarSpace  and load it into memory :) Is there any  plan to simplify StarSpace , since i feel it is not clear as fastText. There is no clear docs and examples

So , i have a big faith in your style , and i hope to see a step form you in this regard

With Respect

**Comment by loretoparisi** [comment]
@beshoo thanks a lot, and thank you for the suggestion, I'm going to add StartSpace soon.

**Comment by loretoparisi** [comment]
unfortunately cannot afford time in porting Starspace, also due to a lose of interest in the Starspace project.
