### ISSUE TITLE
INFO: Could not find files for the given pattern(s).

### ISSUE THREAD

**Issue by vladikus10** [loretoparisi/fasttext.js#6]
I'm trying to run the module on Windows. When I try to initialize it like so:
```
const FastText = require('fasttext.js');

const fastText = new FastText({
    serializeTo: './model',
    trainFile: './train.txt'
});
```
I receive the error: `INFO: Could not find files for the given pattern(s).`.
Yes, I definitely have a *train.txt* file in the same folder as *index.js* (where I execute this code). I even tried using `path.join(__dirname, '/train.txt')`, however I got the same result.

**Comment by loretoparisi** [comment]
@vladikus10 thanks to point this out. Let me check, I guess it could be a path separator issue that I have forgot somewhere.

**Comment by alvinwoon** [comment]
i am having issues with running fasttext in Linux (ubuntu / debian) as well due to the path issues with model file. PM2 start doesn't work. On mac it runs fine.
