### ISSUE TITLE
ERROR: Cannot install via Docker

### ISSUE THREAD

**Issue by KangHyeongMin** [loretoparisi/fasttext.js#9]
### Steps to reproduce
1. Clone project
2. Build the docker image
`$ docker build -t fasttext.js .`
3. Run server by docker
`$ docker run --rm -it -p 3000:3000 fasttext.js node fasttext.js/examples/server.js `

### Expected behaviour
Server starting on docker with below message
```
model loaded
server is listening on 3000
```
### Actual behaviour
Fail to start server on docker with below message
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
```

**Comment by loretoparisi** [comment]
@KangHyeongMin I thinks that was the same issue there :)

**Comment by loretoparisi** [comment]
Thanks! Closed per PR https://github.com/loretoparisi/fasttext.js/pull/10
